__MODULES__ = "Blackbox" 
__HELP__ = """Command Help **Blackbox** 
 
**Basic commands**  
    **You can answer question to blackbox ai** 
        `{0}blackbox` (question) 
    **You can answer about image to blackbox ai** 
        `{0}blackbox` (reply photo) (question) 
    **You can generate image to blackbox ai** 
        `{0}blackbox generate` (prompt) 
 
   {1} 
""" 
 
import traceback 
 
import config 
from Zohun.helpers import CMD, Emoji, Tools 
from Zohun.logger import logger 
 
BLACKBOX_CHAT_URL = "https://api.maelyn.tech/api/blackbox/chat" 
BLACKBOX_IMAGE_URL = "https://api.maelyn.tech/api/blackbox/image" 
BLACKBOX_IMAGINE_URL = "https://api.maelyn.tech/api/blackbox/imagine" 
 
 
@CMD.UBOT("blackbox") 
async def _(client, message): 
    em = Emoji(client) 
    await em.get() 
    pros = await em.get_costum_text() 
    proses = await message.reply(f"{em.proses}**{pros[4]}**") 
 
    prompt = client.get_text(message) 
    if not prompt and not message.reply_to_message: 
        return await proses.edit( 
            f"{em.gagal}**Please give a question or reply with an image and question.**" 
        ) 
 
    try: 
        headers = {"mg-apikey": config.API_MAELYN} 
 
        if message.reply_to_message and message.reply_to_message.photo: 
            if not prompt: 
                return await proses.edit( 
                    f"{em.gagal}**Please provide a question to analyze the image.**" 
                ) 
            photo_url = await Tools.upload_media(message) 
 
            params = {"url": photo_url, "q": prompt} 
            r = await Tools.fetch.get( 
                BLACKBOX_IMAGE_URL, headers=headers, params=params 
            ) 
            data = r.json() 
            return await proses.edit(data.get("result")) 
 
        elif prompt.lower().startswith("generate "): 
            prompt = prompt[9:].strip() 
            if not prompt: 
                return await proses.edit( 
                    f"{em.gagal}**Please reply to a message containing the prompt!\nExample: `{message.text.split()[0]} cute cats`**" 
                ) 
            params = {"prompt": prompt} 
            r = await Tools.fetch.get( 
                BLACKBOX_IMAGINE_URL, headers=headers, params=params 
            ) 
            data = r.json() 
            img_url = data["result"]["url"] 
            return await message.reply_photo( 
                img_url, caption=f"{em.sukses}**Generated by BlackBox**" 
            ) 
 
        else: 
            params = {"q": prompt} 
            r = await Tools.fetch.get(BLACKBOX_CHAT_URL, headers=headers, params=params) 
            data = r.json() 
            return await proses.edit(data.get("result")) 
 
    except Exception as e: 
        logger.error(traceback.format_exc()) 
        return await proses.edit(f"{em.gagal}**Terjadi kesalahan:**\n`{e}`")