import traceback

from config import API_MAELYN
from Zohun import bot
from Zohun.helpers import CMD, Emoji, Tools
from Zohun.logger import logger

__MODULES__ = "Maelyn"
__HELP__ = """<blockquote>Command Help **Maelyn**</blockquote>

<blockquote>**Generate image maelyn** </blockquote>
    **You can generate image ai from Maelyn Art**
        `{0}genai` (prompt)

<b>   {1}</b>
"""


@CMD.UBOT("genai")
async def _(client, message):
    em = Emoji(client)
    await em.get()
    proses_ = await em.get_costum_text()
    proses = await message.reply(f"{em.proses}**{proses_[4]}**")
    prompt = client.get_text(message)
    if not prompt:
        return await proses.edit(
            f"{em.gagal}**Please reply to a message containing the prompt!\n"
            f"Example: `{message.text.split()[0]} beautiful japanese girl`**"
        )
    if prompt in ["Portrait", "portrait"]:
        reso = "Portrait"
    elif prompt in ["Square", "square"]:
        reso = "Square"
    elif prompt in ["Wide", "wide"]:
        reso = "Wide"
    else:
        reso = "Wide"
    try:
        url = f"https://api.maelyn.tech/api/maelynai/imagine?prompt={prompt}&style=hyper_realistic&resolution={reso}&apikey={API_MAELYN}"
        result = await Tools.fetch.get(url)
        if result.status_code == 200:
            data = result.json()["result"]
            command = data.get("prompt")
            model = data.get("model")
            style = data.get("style")
            image = data.get("url")
            await client.send_photo(
                message.chat.id,
                photo=image,
                caption=f"**{em.sukses}**Prompt**: `{command}`\n**Model**: {model}\n**Style**: {style}",
            )
        else:
            await message.reply(
                f"{em.gagal}**Failed to generate: {result.status_code}**"
            )

    except Exception as e:
        logger.error(f"ERROR: {traceback.format_exc()}")
        await message.reply(f"{em.gagal}**Error: {str(e)}**")
    return await proses.delete()


@CMD.UBOT("genai2")
async def _(client, message):
    em = Emoji(client)
    await em.get()
    proses_ = await em.get_costum_text()
    proses = await message.reply(f"{em.proses}**{proses_[4]}**")
    prompt = client.get_text(message)
    if not prompt:
        return await proses.edit(
            f"{em.gagal}**Please reply to a message containing the prompt!\n"
            f"Example: `{message.text.split()[0]} beautiful japanese girl`**"
        )

    try:
        headers = {"mg-apikey": API_MAELYN}
        params = {"prompt": prompt, "resolution": "Portrait"}
        url = "https://api.maelyn.tech/api/txt2img/realistic"
        result = await Tools.fetch.get(url, headers=headers, params=params)
        if result.status_code == 200:
            image = result.json()["result"]
            await client.send_photo(
                message.chat.id,
                photo=image,
                caption=f"**{em.sukses}Generated by @{bot.me.username}**\n",
            )
        else:
            await message.reply(
                f"{em.gagal}**Failed to generate: {result.status_code}**"
            )

    except Exception as e:
        logger.error(f"ERROR: {traceback.format_exc()}")
        await message.reply(f"{em.gagal}**Error: {str(e)}**")
    return await proses.delete()
