import random

import google.generativeai as genai

from config import API_GEMINI
from Zohun import bot
from Zohun.helpers import CMD, Emoji

__MODULES__ = "Pantun"
__HELP__ = """<blockquote>Command Help **Pantun**</blockquote>

<blockquote>**Make pantun**</blockquote>
    **You can create pantun with the theme**
        `{0}pantun percintaan` 
        `{0}pantun bijak`
        `{0}pantun masa depan`
        `{0}pantun motivasi`
        `{0}pantun jenaka`
        `{0}pantun nasihat`
        `{0}pantun agama`
        `{0}pantun random`
        
<blockquote>**Make tebakan**</blockquote>
    **You can create tebakan with the theme**
        `{0}tebakan percintaan` 
        `{0}tebakan bijak`
        `{0}tebakan masa depan`
        `{0}tebakan motivasi`
        `{0}tebakan jenaka`
        `{0}tebakan nasihat`
        `{0}tebakan agama`
        `{0}tebakan random`
        
<blockquote>**Make lelucon**</blockquote>
    **You can create lelucon with the theme**
        `{0}lelucon percintaan` 
        `{0}lelucon bijak`
        `{0}lelucon masa depan`
        `{0}lelucon motivasi`
        `{0}lelucon jenaka`
        `{0}lelucon nasihat`
        `{0}lelucon agama`
        `{0}lelucon random`
        
<blockquote>**Make quotes**</blockquote>
    **You can create quotes with the theme**
        `{0}quotes percintaan` 
        `{0}quotes bijak`
        `{0}quotes masa depan`
        `{0}quotes motivasi`
        `{0}quotes jenaka`
        `{0}quotes nasihat`
        `{0}quotes agama`
        `{0}quotes random`
    
<blockquote>**Make puisi**</blockquote>
    **You can create puisi with the theme**
        `{0}puisi percintaan` 
        `{0}puisi bijak`
        `{0}puisi masa depan`
        `{0}puisi motivasi`
        `{0}puisi jenaka`
        `{0}puisi nasihat`
        `{0}puisi agama`
        `{0}puisi random`

<b>   {1}</b>
"""

RANDOM_PANTUN = [
    "Percintaan",
    "Bijak",
    "Masa Depan",
    "Motivasi",
    "Jenaka",
    "Nasihat",
    "Agama",
    "Random",
]


def gen_pantun(prompt):
    genai.configure(api_key=API_GEMINI)
    aman = {
        "HATE": "BLOCK_NONE",
        "HARASSMENT": "BLOCK_NONE",
        "SEX": "BLOCK_NONE",
        "DANGER": "BLOCK_NONE",
    }

    model = genai.GenerativeModel(
        "models/gemini-1.5-flash",
        system_instruction=(
            """
sesuaikan dengan input yang anda terima.
pastikan output tidak lebih dari 1.
"""
        ),
    )

    try:
        response = model.generate_content(f"{prompt}", safety_settings=aman)
        return f"{response.text}"
    except Exception:
        return None


@CMD.UBOT("pantun|tebakan|lelucon|puisi|quotes")
async def _(client, message):
    emo = Emoji(client)
    await emo.get()
    cmd = message.command[0].lower()
    input_ = client.get_text(message).lower()

    if not input_:
        input_ = random.choice(RANDOM_PANTUN).lower()

    pros = await message.reply(
        f"{emo.proses}<b>Processing to create {cmd} {input_} ..</b>"
    )
    prompt = f"{cmd} {input_}"
    text = gen_pantun(prompt)

    if not text:
        return await pros.edit(f"{emo.gagal}<b>Failed to create {cmd} {input_}.</b>")

    return await pros.edit(
        f"{emo.sukses}<b>Successfully generated {cmd} {input_}:\n\n<code>{text}</code>\n{emo.profil} Generated by: {bot.me.mention}</b>"
    )
